global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: lab7-backend
    metrics_path: /metrics
    static_configs:
      - targets: ["lab7-backend:8000"]
