apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lab7-frontend-ingress
  namespace: lab7-demo
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: lab7.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lab7-frontend
                port:
                  number: 80
