apiVersion: v1
kind: Service
metadata:
  name: lab7-backend
  namespace: {{ .Release.Namespace }}
  labels:
    app: lab7-web-app
    component: backend
    {{- include "lab7-web-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: lab7-web-app
    component: backend
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: 8000
      {{- if eq .Values.backend.service.type "NodePort" }}
      nodePort: {{ .Values.backend.service.nodePort }}
      {{- end }}
