apiVersion: v1
kind: Service
metadata:
  name: lab7-frontend
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30804
---
apiVersion: v1
kind: Service
metadata:
  name: lab7-backend
spec:
  type: NodePort
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30805
