name: lab7-observability

services:
  prometheus:
    image: prom/prometheus:v2.53.3
    container_name: lab7-standalone-prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./compose/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "19090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.enable-lifecycle
    restart: unless-stopped

  tempo:
    image: grafana/tempo:2.6.1
    container_name: lab7-standalone-tempo
    command:
      - "-config.file=/etc/tempo.yaml"
    volumes:
      - ./compose/tempo/tempo.yaml:/etc/tempo.yaml:ro
    ports:
      - "13200:3200"
      - "14317:4317"
      - "14318:4318"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:11.3.0
    container_name: lab7-standalone-grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_DEFAULT_THEME: dark
    volumes:
      - ./compose/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./compose/grafana/dashboards:/var/lib/grafana/dashboards:ro
    ports:
      - "13001:3000"
    depends_on:
      - prometheus
      - tempo
    restart: unless-stopped
