apiVersion: v1
kind: Service
metadata:
  name: lab7-backend
  labels:
    app: lab7-web-app
    component: backend
spec:
  type: ClusterIP
  selector:
    app: lab7-web-app
    component: backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
