apiVersion: v1
kind: Service
metadata:
  name: lab7-frontend
  labels:
    app: lab7-web-app
    component: frontend
spec:
  type: ClusterIP
  selector:
    app: lab7-web-app
    component: frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
