apiVersion: v1
kind: ConfigMap
metadata:
  name: lab7-app-config
data:
  APP_ENV: "продакшен"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://tempo.observability.svc.cluster.local:4318"
  OTEL_SERVICE_NAME: "lab7-backend"
  config.js: |
    window.APP_CONFIG = {
      APP_TITLE: "Лабораторная работа 7 PROD: Prometheus, Grafana и Tempo",
      API_BASE_URL: ""
    };
